select P. PRODUCT_ID, P. PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) AS TOTLA_SALES
from FOOD_PRODUCT P LEFT JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE "%2022-05%"
GROUP BY 2
ORDER BY TOTLA_SALES DESC, P.PRODUCT_ID